FORMAT: 1A
HOST: http://data.iotsdk.com

# WeatherInfo API

# Group API for Weather Info

## Weather Info [/1/weather_info{?y,m,d,city}]

### Get Weather Info [GET]

+ Parameters
    + y (required, int, `2014`) ... year
    + m (required, int, `10`) ... month
    + d (optional, int, `11`) ... day
    + city (required, string, `广州`)

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: 174a4e23dfd14ec888785f0e976c0ed4
            X-XPG-REST-API-Key: 282cac41dece4625b640bb07006e29c8
            Content-Type: application/json

    + Body

            {}

+ Response 200 (application/json)

    + Body
    
            {        
                "date": "2014-10-11",
                "city": "广州",
                "weather": {
                    "0": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "1": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "2": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "3": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "4": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "5": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "6": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "7": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "8": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "9": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "10": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "11": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "12": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "13": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "14": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "15": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "16": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "17": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "18": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "19": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "20": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "21": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "22": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "23": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    }
                }
            }        

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: 174a4e23dfd14ec888785f0e976c0ed4
            X-XPG-REST-API-Key: 282cac41dece4625b640bb07006e29c8
            Content-Type: application/json

    + Body

            {}

+ Response 200 (application/json)

    + Body

            {            
                "weather": {
                    "1": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "2": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "3": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "4": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "5": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "6": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "7": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "8": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "9": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "10": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "11": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "12": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "13": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "14": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "15": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "16": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "17": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "18": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "19": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "20": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "21": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "22": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "23": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "24": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "25": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "26": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "27": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "28": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "29": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "30": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    },
                    "31": {
                        "aqi": 18.2,
                        "pm25": 0,
                        "temp": 13,
                        "humi": 60
                    }
                },
                "city": "广州",
                "month": 10,
                "year": 2014
            }            