FORMAT: 1A
HOST: http://data.iotsdk.com

# WeatherInfo API

## Weather Info [/1/wether_info{?y,m,d,city}]

+ Parameters
    + y (required, int, `2014`) ... year
    + m (required, int, `10`) ... month
    + d (optional, int, `11`) ... day
    + city (required, string, `广州`)

+ Request (application/json)

    + Header
    
            X-XPG-Application-Id: 174a4e23dfd14ec888785f0e976c0ed4
            X-XPG-REST-API-Key: 282cac41dece4625b640bb07006e29c8
            Content-Type: application/json

    + Body

            {}

+ Response 200 (application/json)

    + Body
    
            {
            }
